using EquipTrack.Core.SharedKernel;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace EquipTrack.Infrastructure.Extensions;

internal static class EntityTypeBuilderExtensions
{
    internal static void ConfigureBaseEntity<TEntity>(this EntityTypeBuilder<TEntity> builder)
        where TEntity : BaseEntity
    {
        // Sets the primary key for the entity to the Id property.
        builder
            .HasKey(entity => entity.Id);

        // Configures the Id property to be required (NOT NULL) and not generated by the database.
        builder
            .Property(entity => entity.Id)
            .IsRequired()
            .ValueGeneratedNever();

    }
}
